-- DDL generated by Postico 2.1.1
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE muted_channels (
    server_id text,
    channel_id text,
    ends_at timestamp without time zone,
    CONSTRAINT muted_channels_pkey PRIMARY KEY (server_id, channel_id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX muted_channels_pkey ON muted_channels(server_id text_ops,channel_id text_ops);
