philly = 'https://i.imgur.com/EdYvDjN.gifv'
wheel_of_prizes = 'https://media1.tenor.com/images/a6f3ef0d1f76d12af57aa2baa20f3fca/tenor.gif?itemid=11471078'
wheel_intro = 'https://imgur.com/Ke9osf9'
wheel_spin = 'https://imgur.com/bTuHjT1'
wheel_spinning = 'https://imgur.com/QZNb27v'